# Generated by Django 5.2.8 on 2025-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
